"use client";

import { useMemo, useState } from "react";

type Report = {
title: string;
audience: string;
description: string;
accent: string;
};

const reports: Report[] = [
{
title: "Board Report",
audience: "Board Members",
description:
"Enterprise board presentation summarizing procurement performance, supplier risk, savings forecasts, and strategic opportunities.",
accent: "text-orange-500",
},
{
title: "CEO Brief",
audience: "Chief Executive Officer",
description:
"Growth-focused executive briefing covering supplier expansion, market readiness, procurement momentum, and strategic priorities.",
accent: "text-purple-500",
},
{
title: "CFO Brief",
audience: "Chief Financial Officer",
description:
"Financial procurement report focused on spend control, savings opportunities, forecast accuracy, and award exposure.",
accent: "text-blue-500",
},
{
title: "Procurement Report",
audience: "Procurement Leadership",
description:
"Operational procurement report covering RFQs, suppliers, quote activity, awards, workflow maturity, and performance indicators.",
accent: "text-green-500",
},
];

function buildReport(report: Report) {
return `${report.title}

Audience: ${report.audience}

Executive Summary:
Nexus Pavilion has generated an executive-ready procurement intelligence report focused on supplier performance, RFQ activity, award workflow visibility, savings opportunities, and operational readiness.

Strategic Context:
${report.description}

Key Board Signals:
- Procurement visibility is active across RFQs, quotes, awards, supplier participation, and analytics.
- Executive intelligence modules are available for risk, confidence, supplier ranking, and board-level reporting.
- Soft launch readiness is improving as contact workflow, pricing, legal pages, sitemap, robots, and core procurement workflows are now in place.

Recommended Actions:
1. Review supplier participation and RFQ conversion quality.
2. Monitor awarded volume, savings opportunity, and vendor concentration.
3. Improve executive reporting confidence through continued workflow validation.
4. Prepare final soft launch review before public rollout.

Generated by Nexus Pavilion Executive Reporting Center.`;
}

export default function BoardReportGenerator() {
const [selectedReport, setSelectedReport] = useState<Report | null>(null);
const [copied, setCopied] = useState(false);

const generatedReport = useMemo(() => {
if (!selectedReport) return "";
return buildReport(selectedReport);
}, [selectedReport]);

async function handleCopy() {
if (!generatedReport) return;

try {
await navigator.clipboard.writeText(generatedReport);
setCopied(true);

window.setTimeout(() => {
setCopied(false);
}, 2500);
} catch {
setCopied(false);
}
}

function handleDownloadText() {
if (!selectedReport || !generatedReport) return;

const blob = new Blob([generatedReport], {
type: "text/plain;charset=utf-8",
});

const url = URL.createObjectURL(blob);
const anchor = document.createElement("a");

anchor.href = url;
anchor.download = `${selectedReport.title
.toLowerCase()
.replaceAll(" ", "-")}-nexus-pavilion-report.txt`;

document.body.appendChild(anchor);
anchor.click();
anchor.remove();

URL.revokeObjectURL(url);
}

return (
<section className="mt-8 rounded-3xl border border-slate-200 bg-white p-8">
<p className="text-xs font-black uppercase tracking-[0.25em] text-orange-500">
Executive Reporting Center
</p>

<div className="mt-4 grid gap-8 lg:grid-cols-[1fr_0.85fr]">
<div>
<h2 className="text-4xl font-black text-slate-950">
Board Presentation Generator
</h2>

<p className="mt-4 max-w-4xl text-sm leading-7 text-slate-600">
Generate board-ready procurement narratives for executives, board
members, finance leaders, and procurement teams. Each report creates
a structured executive summary that can be copied, downloaded, and
reused for meetings or soft-launch reviews.
</p>
</div>

<div className="rounded-3xl border border-orange-200 bg-orange-50 p-6">
<p className="text-xs font-black uppercase tracking-[0.2em] text-orange-600">
Launch Ready Output
</p>

<p className="mt-3 text-sm font-semibold leading-7 text-slate-700">
This generator now produces real report content instead of inactive
buttons. PDF and PowerPoint export can be added later after soft
launch.
</p>
</div>
</div>

<div className="mt-8 grid gap-4 md:grid-cols-2">
{reports.map((report) => (
<div
key={report.title}
className="rounded-2xl border border-slate-200 bg-slate-50 p-5"
>
<p
className={`text-xs font-black uppercase tracking-[0.2em] ${report.accent}`}
>
{report.title}
</p>

<p className="mt-2 text-xs font-bold uppercase tracking-[0.18em] text-slate-400">
{report.audience}
</p>

<p className="mt-4 text-sm leading-7 text-slate-700">
{report.description}
</p>

<button
type="button"
onClick={() => {
setSelectedReport(report);
setCopied(false);
}}
className="mt-5 rounded-xl bg-slate-950 px-4 py-3 text-sm font-black text-white transition hover:bg-black"
>
Generate Report
</button>
</div>
))}
</div>

{selectedReport ? (
<div className="mt-8 rounded-3xl border border-slate-200 bg-slate-950 p-6 text-white">
<div className="flex flex-wrap items-start justify-between gap-4">
<div>
<p className="text-xs font-black uppercase tracking-[0.25em] text-orange-400">
Generated Report
</p>

<h3 className="mt-3 text-3xl font-black">
{selectedReport.title}
</h3>

<p className="mt-2 text-sm text-slate-300">
Audience: {selectedReport.audience}
</p>
</div>

<div className="flex flex-wrap gap-3">
<button
type="button"
onClick={handleCopy}
className="rounded-full bg-white px-5 py-3 text-sm font-black text-slate-950 transition hover:bg-slate-100"
>
{copied ? "Copied" : "Copy Report"}
</button>

<button
type="button"
onClick={handleDownloadText}
className="rounded-full bg-orange-500 px-5 py-3 text-sm font-black text-white transition hover:bg-orange-600"
>
Download TXT
</button>
</div>
</div>

<pre className="mt-6 whitespace-pre-wrap rounded-2xl border border-white/10 bg-white/5 p-5 text-sm leading-7 text-slate-200">
{generatedReport}
</pre>
</div>
) : null}

<div className="mt-8 grid gap-4 md:grid-cols-4">
<StatusCard title="Copy Ready" tone="green" />
<StatusCard title="Download Ready" tone="blue" />
<StatusCard title="Board Deck Draft" tone="purple" />
<StatusCard title="Executive Summary" tone="orange" />
</div>
</section>
);
}

function StatusCard({
title,
tone,
}: {
title: string;
tone: "green" | "blue" | "purple" | "orange";
}) {
const className =
tone === "green"
? "border-green-200 bg-green-50 text-green-700"
: tone === "blue"
? "border-blue-200 bg-blue-50 text-blue-700"
: tone === "purple"
? "border-purple-200 bg-purple-50 text-purple-700"
: "border-orange-200 bg-orange-50 text-orange-700";

return (
<div className={`rounded-2xl border p-5 ${className}`}>
<p className="text-xs font-black uppercase">{title}</p>
</div>
);
}